name: Build Vita3KBot

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Build Docker image
        run: docker build -t vita3kbot .

      - name: Create container
        run: docker create --name vita3kbot_container vita3kbot

      - name: Copy publish folder from container
        run: |
          docker cp vita3kbot_container:/app ./publish

      - name: Upload Artifacts
        uses: actions/upload-artifact@v5
        with:
          name: Vita3KBot
          path: publish
